version: '3.8'

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://misight-db.cfmiw488ur7i.us-east-1.rds.amazonaws.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin2024
    ports:
      - "8080:8080"